/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;
import app_busca.Ajust_tabela;
import app_busca.Conexao;
import app_busca.Pdf_Reader;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;

import javax.swing.table.DefaultTableModel;




/**
 *
 * @author Jadiel
 */
public final class Tela_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Principal
     * @param pTexto
     */
    
 
    
     
public void setTexto(String pTexto){  
    this.aviso.setText(pTexto);
    aviso.repaint();
}  
public String getTexto(){  
   return this.aviso.getText();  

}  
    
    public Tela_Principal() {
        
        this.getContentPane().setBackground(Color.BLACK);
   
        this.setResizable(false);
        centralizarComponente(); 
        initComponents();
        

     
                       
    }
    
    
    
    
    
     public void lista_dados_historico(int id_usuario){
         
          Conexao fab = new Conexao();
        fab.abrirConexao();
        
             
             
            
             SimpleDateFormat out = new SimpleDateFormat("dd/MM/yyyy");
        
         String sql = "SELECT * from controle_dados where controle_dados.id_usuario ="+id_usuario+" ORDER BY controle_dados.data_pesquisa DESC, controle_dados.hora DESC";
         
         
             String Data;
            
             //essa lista terá as linhas da sua JTable, preenchi abaixo apenas como exemplo
             /*List<String[]> lista = new ArrayList<>();*/
           
        try {
             fab.rs = fab.stmt.executeQuery(sql);
             /*fab.rs.first();*/
                
          
             
             String[] nomesColunas = new String[] {"Local do Arquivo", "Data Listagem","Hora"};
             
            
            DefaultTableModel modeloTable = new DefaultTableModel (null,nomesColunas){
                 @Override
                 public boolean isCellEditable(int rowIndex, int mColIndex) {  
                return false;  
            }  
        };
                 
             
                       
             
            if (fab.rs != null) {
                while (fab.rs.next()) {
                    
                    Data = out.format(fab.rs.getDate(2));
                    /*lista.add(new String[]{fab.rs.getString(2), Data  });*/
                    
                    Object[] objs = {fab.rs.getString(1), Data,fab.rs.getString(3) };

                     modeloTable.addRow(objs);
                   
                     
                   
                }
                
               /* lista.stream().forEach((String[] s) -> {
                    System.out.println(Arrays.toString(s));
                });*/  
                       
                            
                            final JTable controle_dados = new JTable(); 
                             
                            controle_dados.getTableHeader().setReorderingAllowed(false);
                           
                           
                            
                        
                            controle_dados.setModel(modeloTable);
                           
                           
                           Ajust_tabela.scrollToVisible(controle_dados, 5);
                      
                          ultima_pesquisa.setViewportView(controle_dados);
                          controle_dados.getColumnModel().getColumn(0).setPreferredWidth(500);
                          id_usuario_label.setText(Integer.toString(id_usuario)  );
                     
                         
                       
                      
            } else {

    
            }


         } catch (Exception e) {

                  System.out.println(e.getMessage());

            }
     }
     
     public void centralizarComponente() {  
        Dimension ds = Toolkit.getDefaultToolkit().getScreenSize();  
        Dimension dw = getSize();  
        setLocation((ds.width - dw.width) / 5, (ds.height - dw.height) / 6);  
    }  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        btn_busca = new javax.swing.JButton();
        palavra_chave1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        palavra_chave2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        log_usuario = new javax.swing.JLabel();
        ultima_pesquisa = new javax.swing.JScrollPane();
        id_usuario_label = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        aviso = new javax.swing.JLabel();
        qnt_arq = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_busca.setText("Buscar");
        btn_busca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscaActionPerformed(evt);
            }
        });

        palavra_chave1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Palavra-Chave1:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Palavra-Chave2:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Últimas Pesquisas:");

        log_usuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        log_usuario.setForeground(new java.awt.Color(108, 162, 207));
        log_usuario.setText("Bem-Vindo,");

        ultima_pesquisa.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        id_usuario_label.setText("jLabel6");

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jadiel\\Desktop\\Pendrive\\Monografia\\Aplicacao\\App_Busca\\Imagens\\App_busca_principal.JPG")); // NOI18N
        jLabel4.setText("jLabel4");

        jButton2.setText("Limpar Histórico");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        aviso.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        aviso.setForeground(new java.awt.Color(255, 255, 255));
        aviso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        qnt_arq.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        qnt_arq.setForeground(new java.awt.Color(255, 255, 153));
        qnt_arq.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 153));
        jLabel6.setText("Quantidade de arquivos no PC:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ultima_pesquisa))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(200, 200, 200)
                                .addComponent(btn_busca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(palavra_chave1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(83, 83, 83)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(palavra_chave2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(1, 1, 1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(id_usuario_label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(log_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(112, 112, 112)
                                        .addComponent(aviso, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(qnt_arq, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(51, 51, 51)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(log_usuario)
                    .addComponent(id_usuario_label))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(palavra_chave1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(palavra_chave2)
                            .addComponent(qnt_arq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_busca)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(aviso, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ultima_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        log_usuario.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //Usuário clica no botão sair
        this.dispose();
        Tela_Acesso abrir = new Tela_Acesso ();
        abrir.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_buscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscaActionPerformed
        // TODO add your handling code here:
        // Chamando a classe do pdf_reader
        
         
         qnt_arq.setText("");
        String result = null;
        
         if(palavra_chave1.getText().equals("")
                || palavra_chave2.getText().equals("") ){
             
             JOptionPane.showMessageDialog(null, "Por favor digite as duas palavras");
             
         }else{
             
              Tela_Principal principal = new Tela_Principal();
            String texto = "Pesquisando...";
          principal.aviso.setText(texto);
        
              
             int campo_id;
             int contador;
             System.out.println("Teste1");
             Pdf_Reader executa_app = new Pdf_Reader();
             
              Conexao fab = new Conexao();
              fab.abrirConexao();
        
             
             
              campo_id = Integer.parseInt(id_usuario_label.getText());
             SimpleDateFormat out = new SimpleDateFormat("dd/MM/yyyy");
        
         String sql = "SELECT * from controle_dados where controle_dados.id_usuario ="+campo_id+" ORDER BY controle_dados.data_pesquisa DESC, controle_dados.hora DESC";
         
         
             String Data;
             
            
        try{   
                
              executa_app.deleta_dados(campo_id);
              
                contador = executa_app.lista_diretorio(campo_id);
           
                
                 System.out.println("Teste: %s"+result);
                 
                 executa_app.extrai_dados(campo_id);
                 
                 
                 
              executa_app.compara_dados(palavra_chave1.getText(), palavra_chave2.getText(),campo_id );
                    
              executa_app.deleta_dados(campo_id);
              
            fab.rs = fab.stmt.executeQuery(sql);
             /*fab.rs.first();*/
                
          
             
             String[] nomesColunas = new String[] {"Local do Arquivo", "Data Listagem","Hora"};
             
            
            DefaultTableModel modeloTable = new DefaultTableModel (null,nomesColunas){
                 @Override
                 public boolean isCellEditable(int rowIndex, int mColIndex) {  
                return false;  
            }  
        };
                 
             
                       
             
            if (fab.rs != null) {
                while (fab.rs.next()) {
                    
                    Data = out.format(fab.rs.getDate(2));
                    /*lista.add(new String[]{fab.rs.getString(2), Data  });*/
                    
                    Object[] objs = {fab.rs.getString(1), Data,fab.rs.getString(3) };

                     modeloTable.addRow(objs);
                   
                     
                   
                }
                
               /* lista.stream().forEach((String[] s) -> {
                    System.out.println(Arrays.toString(s));
                });*/  
                       
                            
                            final JTable controle_dados = new JTable(); 
                             
                           controle_dados.getTableHeader().setReorderingAllowed(false);
                           
                           controle_dados.getSelectionModel().setSelectionInterval(1, 1);
                          
                           
                        
                           controle_dados.setModel(modeloTable);
                           Ajust_tabela.scrollToVisible(controle_dados, 5);
                      
                        ultima_pesquisa.setViewportView(controle_dados);
                       
                        controle_dados.getColumnModel().getColumn(0).setPreferredWidth(500);
                        id_usuario_label.setText(Integer.toString(campo_id)  );
                     
                         
                        controle_dados.repaint();
                      
            } else {

    
            }


          
                        System.out.println("Teste6");
                       
            
            /* palavra_chave1.setText("");
              palavra_chave2.setText("");*/
              aviso.setText("");
              qnt_arq.setText(""+contador);
             
             JOptionPane.showMessageDialog(null,"Pesquisa Concluída");   
              
             /*System.in.read();*/
              
          } catch (Exception e) {

                  System.out.println(e.getMessage());

            }
    }//GEN-LAST:event_btn_buscaActionPerformed
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TxcODO add your handling code here:
           int id_usuario;
           
            qnt_arq.setText("");
         id_usuario = Integer.parseInt(id_usuario_label.getText());
             Conexao fab= new Conexao();
                fab.abrirConexao();
             String sql = "delete from controle_dados where controle_dados.id_usuario ="+id_usuario+"";
             PreparedStatement ps = null;
            
        try {
            ps = fab.con.prepareStatement(sql);
        } catch (SQLException ex) {
            Logger.getLogger(Tela_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        try {
            if (ps.executeUpdate() > 0) {
                
                System.out.println("Dados excluídos com sucesso ");
                
                   String[] nomesColunas = new String[] {"Local do Arquivo", "Data Listagem","Hora"};
                   
                   DefaultTableModel modeloTable = new DefaultTableModel (null,nomesColunas){
                 @Override
                 public boolean isCellEditable(int rowIndex, int mColIndex) {  
                return false;  
            }  
        };
                   
                    final JTable controle_dados = new JTable(); 
                             
                           controle_dados.getTableHeader().setReorderingAllowed(false);
                           
                           controle_dados.getSelectionModel().setSelectionInterval(1, 1);
                          
                           
                        
                           controle_dados.setModel(modeloTable);
                           Ajust_tabela.scrollToVisible(controle_dados, 5);
                      
                        ultima_pesquisa.setViewportView(controle_dados);
                       
                        controle_dados.getColumnModel().getColumn(0).setPreferredWidth(500);
                        id_usuario_label.setText(Integer.toString(id_usuario)  );
                     
                         
                        controle_dados.repaint();
                   
                 JOptionPane.showMessageDialog(null,"Histórico Excluído"); 
                
            } else {

                System.out.println("Erro ao excluir ");
                
                 JOptionPane.showMessageDialog(null,"Histórico Vazio"); 

            }
        } catch (SQLException ex) {
            Logger.getLogger(Tela_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Principal().setVisible(true);
                
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel aviso;
    private javax.swing.JButton btn_busca;
    public javax.swing.JLabel id_usuario_label;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JToggleButton jToggleButton1;
    public javax.swing.JLabel log_usuario;
    private javax.swing.JTextField palavra_chave1;
    private javax.swing.JTextField palavra_chave2;
    private javax.swing.JLabel qnt_arq;
    public javax.swing.JScrollPane ultima_pesquisa;
    // End of variables declaration//GEN-END:variables

    public void isMaximumSizeSet(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
